---
apiVersion: v1
data:
  index.html: |
    <h1>Welcome to nginx V1!</h1>
kind: ConfigMap
metadata:
  name: {{.Values.default.images.name}}-{{.Values.default.subnet}}-configmap
---
apiVersion: v1
data:
  index.html: |
    <h1>Welcome to nginx V2!</h1>
kind: ConfigMap
metadata:
  name: {{.Values.default.images.name}}-{{.Values.newversion.subnet}}-configmap
---