---
{{- if eq .Values.gray "gray-v1" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.default.images.name}}-{{.Values.addition}}-{{.Values.gray}}
  labels:
    app: {{.Values.default.images.name}}-{{.Values.addition}}
    version: {{.Values.default.subnet}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.default.images.name}}-{{.Values.addition}}
      version: {{.Values.default.subnet}}
  template:
    metadata:
      labels:
        app: {{.Values.default.images.name}}-{{.Values.addition}}
        version: {{.Values.default.subnet}}
    spec:
      containers:
      - name: {{.Values.default.images.name}}
        image: {{.Values.default.images.repository}}/{{.Values.default.images.repo}}:{{.Values.default.images.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: conf
          readOnly: true
          subPath: index.html
      volumes:
      - configMap:
          defaultMode: 420
          name: {{.Values.default.images.name}}-{{.Values.default.subnet}}-configmap
        name: conf
---
{{- else if eq .Values.gray "gray-v2" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.newversion.images.name}}-{{.Values.addition}}-{{.Values.gray}}
  labels:
    app: {{.Values.newversion.images.name}}-{{.Values.addition}}
    version: {{.Values.newversion.subnet}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.newversion.images.name}}-{{.Values.addition}}
      version: {{.Values.newversion.subnet}}
  template:
    metadata:
      labels:
        app: {{.Values.newversion.images.name}}-{{.Values.addition}}
        version: {{.Values.newversion.subnet}}
    spec:
      containers:
      - name: {{.Values.newversion.images.name}}
        image: {{.Values.newversion.images.repository}}/{{.Values.newversion.images.repo}}:{{.Values.newversion.images.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: conf
          readOnly: true
          subPath: index.html
      volumes:
      - configMap:
          defaultMode: 420
          name: {{.Values.default.images.name}}-{{.Values.newversion.subnet}}-configmap
        name: conf
{{- end }}