---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}
  labels:
    app.kubernetes.io/name: {{.Values.default.images.name}}-{{.Values.addition}}
    version: {{.Values.default.subnet}}
spec:
  serviceName: {{.Values.default.images.name}}-{{.Values.addition}}
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.default.images.name}}-{{.Values.addition}}
      version: {{.Values.default.subnet}}
  template:
    metadata:
      labels:
        version: {{.Values.default.subnet}}
        app.kubernetes.io/name: {{.Values.default.images.name}}-{{.Values.addition}}
    spec:
      containers:
      - name: {{.Release.Name}}
        image: {{.Values.default.images.repository}}/{{.Values.default.images.repo}}:{{.Values.default.images.tag}}
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        envFrom:
        - configMapRef:
            name: {{.Values.default.images.name}}-{{.Values.addition}}-configmap
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
