---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{.Values.gatewayname}}-{{.Values.addition}}
spec:
  selector:
    istio: alb-ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - "ngxgray-test.pionexdev.com"
---
